name: basic test

on:
  push:
    tags:
      - ".*"
    branches:
      - master
  pull_request:
    branches:
      - master
      - feature-2.0

jobs:
  simple-checks:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - uses: pre-commit/action@v3.0.0

  unit-tests:
    runs-on: ubuntu-latest
    needs: simple-checks

    services:
      docker:
        image: docker

      cache:
        image: buchgr/bazel-remote-cache:v2.3.9
        env:
          BAZEL_REMOTE_MAX_SIZE: 5
          BAZEL_REMOTE_DIR: ~/.cache/bazel/disk

    steps:
      - uses: jpribyl/action-docker-layer-caching@v0.1.1
        continue-on-error: true

      - uses: actions/checkout@v3

      - uses: bazelbuild/setup-bazelisk@v2

      - name: load bazel cache
        uses: actions/cache@v3
        with:
          path: "~/.cache/bazel"
          key: bazel

      - run: bazel test --config=ci //tests/unit/...
